/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.*;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author Jan
 */
public class BankDisplay extends javax.swing.JPanel {

    /**
     * Creates new form Bank
     */
    public BankDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLoan = new javax.swing.JLabel();
        labelPayLoan = new javax.swing.JLabel();
        labelCancel = new javax.swing.JLabel();
        btnLoan = new javax.swing.JButton();
        btnPayLoan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();
        labelAmount = new javax.swing.JLabel();
        labelPayable = new javax.swing.JLabel();
        labelUp = new javax.swing.JLabel();
        labelDown = new javax.swing.JLabel();
        labelConfirm = new javax.swing.JLabel();
        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBlue = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(32767, 16));
        btnGreen = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(32767, 16));
        btnPurple = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1248, 552));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLoan.setBackground(new java.awt.Color(255, 255, 255));
        labelLoan.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelLoan.setForeground(new java.awt.Color(255, 255, 255));
        labelLoan.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelLoan.setText("Loan from bank");
        add(labelLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 130, 40));

        labelPayLoan.setBackground(new java.awt.Color(255, 255, 255));
        labelPayLoan.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelPayLoan.setForeground(new java.awt.Color(255, 255, 255));
        labelPayLoan.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelPayLoan.setText("Pay Loan");
        add(labelPayLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 80, 40));

        labelCancel.setBackground(new java.awt.Color(255, 255, 255));
        labelCancel.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelCancel.setForeground(new java.awt.Color(255, 255, 255));
        labelCancel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelCancel.setText("Cancel");
        add(labelCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 80, 40));

		btnLoan.setActionCommand ("Loan from bank");
        add(btnLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 50, 40));

        btnPayLoan.setActionCommand ("Pay loan");
        add(btnPayLoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 50, 40));

        btnCancel.setActionCommand ("Cancel transaction");
        add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 50, 40));

        labelName.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelName.setText("");
        add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 150, -1));

        labelAmount.setBackground(new java.awt.Color(255, 255, 255));
        labelAmount.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelAmount.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelAmount.setOpaque(true);
		labelAmount.setText ("$ 0 ");
        add(labelAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 203, 150, 30));

        labelPayable.setBackground(new java.awt.Color(255, 255, 255));
        labelPayable.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelPayable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPayable.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        labelPayable.setOpaque(true);
		labelPayable.setText ("$ 0 ");
        add(labelPayable, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 150, 30));

        labelUp.setBackground(new java.awt.Color(255, 255, 255));
        labelUp.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelUp.setForeground(new java.awt.Color(255, 255, 255));
        labelUp.setText("Increase");
        add(labelUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 130, 40));

        labelDown.setBackground(new java.awt.Color(255, 255, 255));
        labelDown.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelDown.setForeground(new java.awt.Color(255, 255, 255));
        labelDown.setText("Decrease");
        add(labelDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 130, 40));

        labelConfirm.setBackground(new java.awt.Color(255, 255, 255));
        labelConfirm.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        labelConfirm.setForeground(new java.awt.Color(255, 255, 255));
        labelConfirm.setText("Confirm");
        add(labelConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 130, 40));

        btnUp.setActionCommand ("Increase amount");
        add(btnUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 50, 40));

        btnDown.setActionCommand ("Decrease amount");
        add(btnDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 50, 40));

        btnConfirm.setActionCommand ("Confirm transaction");
        add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 50, 40));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        btnBlue.setBackground(new java.awt.Color(93, 93, 93));
        btnBlue.setForeground(new java.awt.Color(93, 93, 93));
        btnBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/creditBlue.png"))); // NOI18N
        btnBlue.setMaximumSize(new java.awt.Dimension(216, 136));
        btnBlue.setMinimumSize(new java.awt.Dimension(206, 128));
        btnBlue.setPreferredSize(new java.awt.Dimension(216, 136));
		btnBlue.setActionCommand ("Player 1 transaction");
        jPanel1.add(btnBlue);
        jPanel1.add(filler1);

        btnGreen.setBackground(new java.awt.Color(93, 93, 93));
        btnGreen.setForeground(new java.awt.Color(93, 93, 93));
        btnGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/creditGreen.png"))); // NOI18N
        btnGreen.setMaximumSize(new java.awt.Dimension(216, 136));
        btnGreen.setMinimumSize(new java.awt.Dimension(206, 128));
        btnGreen.setPreferredSize(new java.awt.Dimension(216, 136));
        btnGreen.setActionCommand ("Player 2 transaction");
        jPanel1.add(btnGreen);
        jPanel1.add(filler2);

        btnPurple.setBackground(new java.awt.Color(93, 93, 93));
        btnPurple.setForeground(new java.awt.Color(93, 93, 93));
        btnPurple.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/creditPurple.png"))); // NOI18N
        btnPurple.setMaximumSize(new java.awt.Dimension(216, 136));
        btnPurple.setMinimumSize(new java.awt.Dimension(206, 128));
        btnPurple.setPreferredSize(new java.awt.Dimension(216, 136));
		btnPurple.setActionCommand ("Player 3 transaction");
        jPanel1.add(btnPurple);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 240, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/bank.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void setActionListener (ActionListener listener) {
		btnLoan.addActionListener (listener);
		btnPayLoan.addActionListener (listener);
		btnCancel.addActionListener (listener);
		btnUp.addActionListener (listener);
		btnDown.addActionListener (listener);
		btnConfirm.addActionListener (listener);
		btnBlue.addActionListener (listener);
		btnGreen.addActionListener (listener);
		btnPurple.addActionListener (listener);
	}
	
	public void setBankMode (int mode) {
		if (mode == 1 || mode == -1) {
			labelAmount.setText ("$ 0 ");
			bankMode = mode;
			count = 0;
			if (mode == 1) {
				amountIncrement = 20000;
				labelPayable.setText ("$ 0 ");
			}
			else {
				amountIncrement = 25000;
				labelPayable.setText ("- $ 0 ");
			}
		}
	}
	
	// public void changeAccountName (String name) {
		// resetDisplay ();
		// labelName.setText (name);
	// }
	
	public void changeCurAccount (Player player) {
		resetDisplay ();
		openedAccount = player;
		setBankMode (1);
		labelName.setText (openedAccount.getName ());
	}
	
	public void changeDisplayAmount (int change) {
		if (openedAccount != null
			&& (bankMode == 1
				|| bankMode == -1 && openedAccount.getLoan () >= (count + change) * 25000))
			count += change;
		
		if (count < 0)
			count = 0;
		else if (count > 5)
			count = 5;
		
		amount = count * amountIncrement;
		payable = count * payableIncrement;
		
		labelAmount.setText ("$ " + NumberFormat.getNumberInstance(Locale.US).format(amount) + " ");
		if (bankMode == 1)
			labelPayable.setText ("$ " + NumberFormat.getNumberInstance(Locale.US).format(payable) + " ");
		else if (bankMode == -1)
			labelPayable.setText ("- $ " + NumberFormat.getNumberInstance(Locale.US).format(payable) + " ");
	}
	
	public void resetDisplay () {
		count = 0;
		labelName.setText ("");
		openedAccount = null;
		labelAmount.setText ("$ 0 ");
		if (bankMode == 1)
			labelPayable.setText ("$ 0 ");
		else if (bankMode == -1)
			labelPayable.setText ("- $ 0 ");
	}
	
	public void confirmTransaction () {
		openedAccount.transactLoan (count * bankMode);
	}
	
	// public Player getOpenedAccount () {
		// return openedAccount;
	// }
	
	public void drawVariableObjects (int num) {
		if (num == 2)
			btnPurple.setVisible (false);
		else
			btnPurple.setVisible (true);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBlue;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnGreen;
    private javax.swing.JButton btnLoan;
    private javax.swing.JButton btnPayLoan;
    private javax.swing.JButton btnPurple;
    private javax.swing.JButton btnUp;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelCancel;
    private javax.swing.JLabel labelConfirm;
    private javax.swing.JLabel labelDown;
    private javax.swing.JLabel labelLoan;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPayLoan;
    private javax.swing.JLabel labelPayable;
    private javax.swing.JLabel labelUp;
	private int amount;
	private int payable;
	private int bankMode = 1;
	private Player openedAccount;
	private static int amountIncrement = 20000;
	private static int payableIncrement = 25000;
	private static int count = 0;
	
    // End of variables declaration//GEN-END:variables
}
