/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jan
 */
public class EndScreen extends javax.swing.JPanel {

    /**
     * Creates new form EndScreen
     */
    public EndScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 64), new java.awt.Dimension(0, 64), new java.awt.Dimension(32767, 64));
        labelLogo = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 64), new java.awt.Dimension(0, 64), new java.awt.Dimension(32767, 64));
        panel = new javax.swing.JPanel();
        summaryBox = new javax.swing.JPanel();
        boxSecond = new javax.swing.JPanel();
        labelSecond = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        labelIcon = new javax.swing.JLabel[3];
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        labelName = new javax.swing.JLabel[3];
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        labelMoney = new javax.swing.JLabel[3];
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        boxFirst = new javax.swing.JPanel();
        labelFirst = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(32767, 16));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 48), new java.awt.Dimension(0, 48), new java.awt.Dimension(32767, 48));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        boxThird = new javax.swing.JPanel();
        labelThird = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 48), new java.awt.Dimension(0, 48), new java.awt.Dimension(32767, 48));
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 16), new java.awt.Dimension(0, 16), new java.awt.Dimension(32767, 16));
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        labelClosing = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 64), new java.awt.Dimension(0, 64), new java.awt.Dimension(32767, 64));
		
		for (int i = 0; i < 3; i++) {
			labelName[i] = new javax.swing.JLabel ();
			labelMoney[i] = new javax.swing.JLabel ();
			labelIcon[i] = new javax.swing.JLabel ();
		}
		
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(filler1);

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/thatslife.png"))); // NOI18N
        labelLogo.setAlignmentX(0.5F);
        labelLogo.setAlignmentY(1.0F);
        add(labelLogo);
        add(filler2);

        panel.setOpaque(false);

        summaryBox.setOpaque(false);
        summaryBox.setPreferredSize(new java.awt.Dimension(512, 288));
        summaryBox.setLayout(new javax.swing.BoxLayout(summaryBox, javax.swing.BoxLayout.LINE_AXIS));

        boxSecond.setAlignmentX(0.5F);
        boxSecond.setOpaque(false);
        boxSecond.setPreferredSize(new java.awt.Dimension(160, 256));
        boxSecond.setLayout(new javax.swing.BoxLayout(boxSecond, javax.swing.BoxLayout.Y_AXIS));

        labelSecond.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelSecond.setText("2nd");
        labelSecond.setAlignmentX(0.5F);
        boxSecond.add(labelSecond);
        boxSecond.add(filler7);

        labelIcon[1].setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerBlue.png"))); // NOI18N
        labelIcon[1].setAlignmentX(0.5F);
        boxSecond.add(labelIcon[1]);
        boxSecond.add(filler13);

        labelName[1].setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelName[1].setText("Did not play");
        labelName[1].setAlignmentX(0.5F);
        boxSecond.add(labelName[1]);
        boxSecond.add(filler8);

        labelMoney[1].setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelMoney[1].setText("$ 0");
        labelMoney[1].setAlignmentX(0.5F);
        boxSecond.add(labelMoney[1]);
        boxSecond.add(filler14);

        summaryBox.add(boxSecond);
        summaryBox.add(filler6);

        boxFirst.setOpaque(false);
        boxFirst.setPreferredSize(new java.awt.Dimension(160, 256));
        boxFirst.setLayout(new javax.swing.BoxLayout(boxFirst, javax.swing.BoxLayout.Y_AXIS));

        labelFirst.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelFirst.setText("1st");
        labelFirst.setAlignmentX(0.5F);
        boxFirst.add(labelFirst);
        boxFirst.add(filler9);

        labelIcon[0].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon[0].setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerGreen.png"))); // NOI18N
        labelIcon[0].setAlignmentX(0.5F);
        boxFirst.add(labelIcon[0]);
        boxFirst.add(filler11);

        labelName[0].setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelName[0].setText("Did not play");
        labelName[0].setAlignmentX(0.5F);
        boxFirst.add(labelName[0]);
        boxFirst.add(filler10);

        labelMoney[0].setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelMoney[0].setText("$ 0");
        labelMoney[0].setAlignmentX(0.5F);
        boxFirst.add(labelMoney[0]);
        boxFirst.add(filler12);

        summaryBox.add(boxFirst);
        summaryBox.add(filler5);

        boxThird.setOpaque(false);
        boxThird.setPreferredSize(new java.awt.Dimension(160, 256));
        boxThird.setLayout(new javax.swing.BoxLayout(boxThird, javax.swing.BoxLayout.Y_AXIS));

        labelThird.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelThird.setText("3rd");
        labelThird.setAlignmentX(0.5F);
        boxThird.add(labelThird);
        boxThird.add(filler15);

        labelIcon[2].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon[2].setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerPurple.png"))); // NOI18N
        labelIcon[2].setAlignmentX(0.5F);
        boxThird.add(labelIcon[2]);
        boxThird.add(filler16);

        labelName[2].setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelName[2].setText("Did not play");
        labelName[2].setAlignmentX(0.5F);
        boxThird.add(labelName[2]);
        boxThird.add(filler17);

        labelMoney[2].setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        labelMoney[2].setText("$ 0");
        labelMoney[2].setAlignmentX(0.5F);
        boxThird.add(labelMoney[2]);
        boxThird.add(filler18);

        summaryBox.add(boxThird);

        panel.add(summaryBox);

        add(panel);
        add(filler3);

        labelClosing.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        labelClosing.setText("Thank you for playing!");
        labelClosing.setAlignmentX(0.5F);
        add(labelClosing);
        add(filler4);
    }// </editor-fold>//GEN-END:initComponents

	public void setText (Player[] players) {
		for (int i = 0; i < players.length; i++)
			if (players[i] != null) {
				labelName[i].setText (players[i].getName ());
				labelMoney[i].setText ("" + players[i].getMoney ());
			}
	}
	
	public void setIcons (String[] names) {
		String[] icons = new String[3];
		icons[0] = "./graphics/playerBlue.png";
		icons[1] = "./graphics/playerGreen.png";
		icons[2] = "./graphics/playerPurple.png";
		
		for (int i = 0; i < names.length; i++) {
			if (names[i] == null)
				names[i] = "Player " + (i + 1);
			for (int j = 0; j < labelName.length; j++)
				if (labelName[j].getText ().equals (names[i]))
					labelIcon[j].setIcon(new javax.swing.ImageIcon(getClass().getResource(icons[i])));
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxFirst;
    private javax.swing.JPanel boxSecond;
    private javax.swing.JPanel boxThird;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel[] labelIcon;
    private javax.swing.JLabel labelClosing;
    private javax.swing.JLabel labelFirst;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSecond;
    private javax.swing.JLabel labelThird;
    private javax.swing.JLabel labelMoney[];
    private javax.swing.JLabel labelName[];
    private javax.swing.JPanel panel;
    private javax.swing.JPanel summaryBox;
    // End of variables declaration//GEN-END:variables
}
