/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jan
 */
public class MapDisplay extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MapDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerBox = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        box1 = new javax.swing.JPanel();
        player1 = new javax.swing.JPanel();
        iconP1 = new javax.swing.JLabel();
        names = new javax.swing.JLabel [3];
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        box2 = new javax.swing.JPanel();
        player2 = new javax.swing.JPanel();
        iconP2 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        box3 = new javax.swing.JPanel();
        player3 = new javax.swing.JPanel();
        iconP3 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        background = new javax.swing.JLabel();
		
		for (int i = 0; i < 3; i++)
			names[i] = new javax.swing.JLabel ();

        setMaximumSize(new java.awt.Dimension(1248, 552));
        setMinimumSize(new java.awt.Dimension(1248, 552));
        setPreferredSize(new java.awt.Dimension(1248, 552));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerBox.setMaximumSize(new java.awt.Dimension(512, 256));
        playerBox.setPreferredSize(new java.awt.Dimension(512, 256));
        playerBox.setLayout(new javax.swing.BoxLayout(playerBox, javax.swing.BoxLayout.LINE_AXIS));
        playerBox.add(filler1);

        box1.setLayout(new javax.swing.BoxLayout(box1, javax.swing.BoxLayout.LINE_AXIS));

        player1.setPreferredSize(new java.awt.Dimension(48, 72));

        iconP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerBlue.png"))); // NOI18N

        names[0].setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        names[0].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        names[0].setText("");

        javax.swing.GroupLayout player1Layout = new javax.swing.GroupLayout(player1);
        player1.setLayout(player1Layout);
        player1Layout.setHorizontalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(names[0], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(player1Layout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(iconP1)
                    .addGap(0, 32, Short.MAX_VALUE)))
        );
        player1Layout.setVerticalGroup(
            player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player1Layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(names[0]))
            .addGroup(player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(player1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(iconP1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        box1.add(player1);
        box1.add(filler2);

        playerBox.add(box1);

        box2.setLayout(new javax.swing.BoxLayout(box2, javax.swing.BoxLayout.LINE_AXIS));

        player2.setPreferredSize(new java.awt.Dimension(48, 72));

        iconP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerGreen.png"))); // NOI18N

        names[1].setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        names[1].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        names[1].setText("");

        javax.swing.GroupLayout player2Layout = new javax.swing.GroupLayout(player2);
        player2.setLayout(player2Layout);
        player2Layout.setHorizontalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(names[1], javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(player2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(iconP2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        player2Layout.setVerticalGroup(
            player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player2Layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(names[1]))
            .addGroup(player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(player2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(iconP2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        box2.add(player2);
        box2.add(filler3);

        playerBox.add(box2);

        // box3.setLayout(new javax.swing.BoxLayout(box3, javax.swing.BoxLayout.LINE_AXIS));

        // player3.setPreferredSize(new java.awt.Dimension(48, 72));

        // iconP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerPurple.png"))); // NOI18N

        // names[2].setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        // names[2].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        // names[2].setText("Player 3");

        // javax.swing.GroupLayout player3Layout = new javax.swing.GroupLayout(player3);
        // player3.setLayout(player3Layout);
        // player3Layout.setHorizontalGroup(
            // player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            // .addGroup(player3Layout.createSequentialGroup()
                // .addContainerGap()
                // .addComponent(names[2], javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                // .addContainerGap())
            // .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                // .addGroup(player3Layout.createSequentialGroup()
                    // .addGap(0, 0, Short.MAX_VALUE)
                    // .addComponent(iconP3)
                    // .addGap(0, 0, Short.MAX_VALUE)))
        // );
        // player3Layout.setVerticalGroup(
            // player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            // .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player3Layout.createSequentialGroup()
                // .addGap(0, 90, Short.MAX_VALUE)
                // .addComponent(names[2]))
            // .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                // .addGroup(player3Layout.createSequentialGroup()
                    // .addGap(0, 0, Short.MAX_VALUE)
                    // .addComponent(iconP3)
                    // .addGap(0, 0, Short.MAX_VALUE)))
        // );

        // box3.add(player3);
        // box3.add(filler4);

        // playerBox.add(box3);

        add(playerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 420, 120));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/map.png"))); // NOI18N
        background.setToolTipText("");
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents



	public void drawVariableObjects () {
		
		box3.setLayout(new javax.swing.BoxLayout(box3, javax.swing.BoxLayout.LINE_AXIS));

        player3.setPreferredSize(new java.awt.Dimension(48, 72));

        iconP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerPurple.png"))); // NOI18N

        names[2].setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        names[2].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        names[2].setText("");

        javax.swing.GroupLayout player3Layout = new javax.swing.GroupLayout(player3);
        player3.setLayout(player3Layout);
        player3Layout.setHorizontalGroup(
            player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(names[2], javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(player3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(iconP3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        player3Layout.setVerticalGroup(
            player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player3Layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(names[2]))
            .addGroup(player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(player3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(iconP3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        box3.add(player3);
        box3.add(filler4);

        playerBox.add(box3);
	}
	
	public void setNames (Player[] players) {
		for (int i = 0; i < players.length; i++)
			if (players[i] != null)
				names[i].setText (players[i].getName ());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel box1;
    private javax.swing.JPanel box2;
    private javax.swing.JPanel box3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel iconP1;
    private javax.swing.JLabel iconP2;
    private javax.swing.JLabel iconP3;
    private javax.swing.JLabel[] names;
    private javax.swing.JPanel player1;
    private javax.swing.JPanel player2;
    private javax.swing.JPanel player3;
    private javax.swing.JPanel playerBox;
    // End of variables declaration//GEN-END:variables
}
