/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
import java.awt.event.*;

/**
 *
 * @author Jan
 */
public class NameScreen extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NameScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 64), new java.awt.Dimension(0, 64), new java.awt.Dimension(32767, 64));
        iconLogo = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        player1 = new javax.swing.JPanel();
        nameP1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        iconP1 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        txtP1 = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        player2 = new javax.swing.JPanel();
        nameP2 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        iconP2 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        txtP2 = new javax.swing.JTextField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        player3 = new javax.swing.JPanel();
        nameP3 = new javax.swing.JLabel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        iconP3 = new javax.swing.JLabel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 0), new java.awt.Dimension(16, 32767));
        txtP3 = new javax.swing.JTextField();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 96), new java.awt.Dimension(0, 96), new java.awt.Dimension(32767, 96));
        buttons = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(32, 0), new java.awt.Dimension(32, 0), new java.awt.Dimension(32, 32767));
        btnConfirm = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(filler1);

        iconLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/thatslife.png"))); // NOI18N
        iconLogo.setAlignmentX(0.5F);
        iconLogo.setAlignmentY(1.0F);
        iconLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(iconLogo);
        add(filler2);

        player1.setBackground(new java.awt.Color(255, 255, 255));
        player1.setMaximumSize(new java.awt.Dimension(32767, 72));

        nameP1.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        nameP1.setText("Player 1");
        player1.add(nameP1);
        player1.add(filler3);

        iconP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerBlue.png"))); // NOI18N
        player1.add(iconP1);
        player1.add(filler4);

        txtP1.setBackground(new java.awt.Color(240, 240, 240));
        txtP1.setPreferredSize(new java.awt.Dimension(256, 32));
        
        player1.add(txtP1);

        add(player1);
        add(filler5);

        player2.setBackground(new java.awt.Color(255, 255, 255));
        player2.setMaximumSize(new java.awt.Dimension(32767, 72));

        nameP2.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        nameP2.setText("Player 2");
        player2.add(nameP2);
        player2.add(filler6);

        iconP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerGreen.png"))); // NOI18N
        player2.add(iconP2);
        player2.add(filler7);

        txtP2.setBackground(new java.awt.Color(240, 240, 240));
        txtP2.setPreferredSize(new java.awt.Dimension(256, 32));
        
        player2.add(txtP2);

        add(player2);
        add(filler8);

        player3.setBackground(new java.awt.Color(255, 255, 255));
        player3.setMaximumSize(new java.awt.Dimension(32767, 72));

        nameP3.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 24)); // NOI18N
        nameP3.setText("Player 3");
        player3.add(nameP3);
        player3.add(filler9);

        iconP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/playerPurple.png"))); // NOI18N
        player3.add(iconP3);
        player3.add(filler10);

        txtP3.setBackground(new java.awt.Color(240, 240, 240));
        txtP3.setPreferredSize(new java.awt.Dimension(256, 32));
        txtP3.setDisabledTextColor(new java.awt.Color(128, 128, 128));
        
        player3.add(txtP3);

        add(player3);
        add(filler11);

        buttons.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setText("Back");
        btnBack.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBack.setMaximumSize(new java.awt.Dimension(64, 32));
        btnBack.setPreferredSize(new java.awt.Dimension(64, 32));
        btnBack.setActionCommand ("Back to start screen");
		
        buttons.add(btnBack);
        buttons.add(filler12);

        btnConfirm.setText("Confirm");
        btnConfirm.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnConfirm.setMaximumSize(new java.awt.Dimension(64, 32));
        btnConfirm.setMinimumSize(new java.awt.Dimension(32, 21));
        btnConfirm.setPreferredSize(new java.awt.Dimension(64, 32));
		btnConfirm.setActionCommand ("Confirm names");
        buttons.add(btnConfirm);

        add(buttons);
    }// </editor-fold>//GEN-END:initComponents

	public void setActionListener (ActionListener listener) {
		btnBack.addActionListener (listener);
		btnConfirm.addActionListener (listener);
	}
	
	public void enableFields (int num) {
		if (num == 2) {
			txtP3.setText ("[3 player mode only]");
			txtP3.setHorizontalAlignment (javax.swing.SwingConstants.CENTER);
			txtP3.setEnabled (false);
		}
		else {
			txtP3.setText ("");
			txtP3.setHorizontalAlignment (javax.swing.SwingConstants.LEADING);
			txtP3.setEnabled (true);
		}
	}
	
	public void clearFields () {
		txtP1.setText ("");
		txtP2.setText ("");
		txtP3.setText ("");
	}
	
	public String[] getNames () {
		String names[] = new String[2];
		if (txtP3.isEnabled ())
			names = new String[3];
		
		names[0] = txtP1.getText ();
		names[1] = txtP2.getText ();
		if (txtP3.isEnabled ()) {
			names[2] = txtP3.getText ();
		}
		
		for (int i = 0; i < names.length; i++)
			if (names[i] != null)
				if (names[i].equals (""))
					names[i] = null;
		
		return names;
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JPanel buttons;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel iconLogo;
    private javax.swing.JLabel iconP1;
    private javax.swing.JLabel iconP2;
    private javax.swing.JLabel iconP3;
    private javax.swing.JLabel nameP1;
    private javax.swing.JLabel nameP2;
    private javax.swing.JLabel nameP3;
    private javax.swing.JPanel player1;
    private javax.swing.JPanel player2;
    private javax.swing.JPanel player3;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP2;
    private javax.swing.JTextField txtP3;
    // End of variables declaration//GEN-END:variables
}
