/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
 import java.awt.event.*;

/**
 *
 * @author Jan
 */
public class StartScreen extends javax.swing.JPanel {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 64), new java.awt.Dimension(0, 64), new java.awt.Dimension(32767, 64));
        labelLogo = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        labelGreeting = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 32), new java.awt.Dimension(0, 32), new java.awt.Dimension(32767, 32));
        buttons = new javax.swing.JPanel();
        btnTwo = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(64, 0), new java.awt.Dimension(64, 0), new java.awt.Dimension(64, 32767));
        btnThree = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(filler4);

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/thatslife.png"))); // NOI18N
        labelLogo.setAlignmentX(0.5F);
        labelLogo.setAlignmentY(1.0F);
        add(labelLogo);
        add(filler3);

        labelGreeting.setFont(new java.awt.Font(GUI.GAME_FONT, 0, 48)); // NOI18N
        labelGreeting.setText("Select mode");
        labelGreeting.setAlignmentX(0.5F);
        add(labelGreeting);
        add(filler5);

        buttons.setBackground(new java.awt.Color(255, 255, 255));

        btnTwo.setBackground(new java.awt.Color(0, 0, 0));
        btnTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/2player.png"))); // NOI18N
        btnTwo.setPreferredSize(new java.awt.Dimension(196, 324));
		btnTwo.setActionCommand ("Two player mode");
	    
        buttons.add(btnTwo);
        buttons.add(filler1);

        btnThree.setBackground(new java.awt.Color(0, 0, 0));
        btnThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("./graphics/3player.png"))); // NOI18N
        btnThree.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnThree.setPreferredSize(new java.awt.Dimension(196, 324));
		btnThree.setActionCommand ("Three player mode");
		
        buttons.add(btnThree);

        add(buttons);
    }// </editor-fold>//GEN-END:initComponents

    public void setActionListener (ActionListener listener) {
		btnTwo.addActionListener (listener);
		btnThree.addActionListener (listener);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnThree;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelGreeting;
    private javax.swing.JPanel buttons;
    // End of variables declaration//GEN-END:variables
}
